export const STRINGS = {
  ar: {
    brand: 'محلل المخاطر الائتمانية',
    navHome: 'الرئيسية',
    navHowItWorks: 'كيف يعمل',
    navResults: 'النتائج',
    navContact: 'تواصل',
    getStarted: 'ابدأ الآن',
    heroEyebrow: 'منصة قرارات ائتمانية ذكية',
    heroHeading: 'رأس المال، البيانات، والخدمة — تعريف جديد للنمو.',
    heroSub: 'تحليل ائتماني فوري مدعوم بنماذج التعلم الآلي ومعايير ساما، يمنحك قرارًا واضحًا خلال ثوانٍ.',
    ctaPrimary: 'افتح حسابك',
    ctaSecondary: 'استكشف الأسواق',
    statsTitle: 'نتائج تستحق الاهتمام',
    statsSub: 'أرقام حقيقية تعكس قيمة ما نقدمه.',
    stat1Value: '28٪',
    stat1Label: 'إجمالي العائد للمحافظ المُحسَّنة',
    stat2Value: '45 د/أسبوع',
    stat2Label: 'وقت تم توفيره عبر الاستراتيجيات الآلية',
    stat3Value: 'متوافق مع SAMA',
    stat3Label: 'مستشار استثماري مرخّص يضمن الأمان والامتثال',
    pickBank: 'اختر نوع البنك',
    bankConservative: 'البنك المحافظ',
    bankAggressive: 'البنك الجريء',
    bankConservativeDesc: 'فائدة 2٪–4٪ ثابتة، حد أدنى لراتب 5,000 ريال',
    bankAggressiveDesc: 'فائدة 7٪–15٪ متغيرة، حد أدنى لراتب 4,000 ريال',
    pdThreshold: 'حد احتمالية التعثر',
    minScore: 'الحد الأدنى لدرجة سمة',
    interestRate: 'معدل الفائدة',
    formTitle: 'بيانات الطلب',
    grossSalary: 'الراتب الشهري (ريال)',
    loanAmount: 'مبلغ القرض (ريال)',
    loanMonths: 'مدة القرض (شهر)',
    employmentType: 'نوع التوظيف',
    employmentGov: 'حكومي',
    employmentPriv: 'خاص',
    employmentSelf: 'عمل حر',
    age: 'العمر',
    submitBtn: 'تقييم الطلب',
    simulateBtn: 'محاكاة سحب بيانات الجهات (سمة + التأمينات)',
    simahTitle: 'الملف الائتماني (محاكاة)',
    simahTotalDebt: 'إجمالي الدين',
    simahMaxOverdue: 'أعلى تأخر سداد',
    simahInquiries: 'استعلامات الشهر',
    simahHistory: 'متوسط عمر السجل (يوم)',
    simahDpd: 'أعلى تأخر بالأيام',
    gosiTitle: 'بيانات التأمينات (محاكاة)',
    gosiYears: 'سنوات الخدمة',
    gosiSector: 'قطاع صاحب العمل',
    gosiStatus: 'حالة الاشتراك',
    gosiActive: 'نشط',
    gosiSectorGov: 'حكومي',
    gosiSectorPriv: 'خاص',
    gosiSectorSelf: 'عمل حر',
    gosiYearsUnit: 'سنة',
    gosiOverrideHint: 'تجاوز يدوي مفعّل — يتم تعبئة القطاع تلقائيًا من محاكاة التأمينات ولكن يمكن تعديله (وضع المحاكاة)',
    samaMinEmployment: 'لا يستوفي الحد الأدنى لمدة الخدمة وفق ساما (حكومي: 3 أشهر / خاص: 12 شهرًا)',
    samaStatus: 'الالتزام بحدود ساما',
    samaWithinGov: 'ضمن حد ساما (45٪ للقطاع الحكومي)',
    samaWithinPriv: 'ضمن حد ساما (33٪)',
    samaExceedsGov: 'يتجاوز حد ساما (45٪ للقطاع الحكومي)',
    samaExceedsPriv: 'يتجاوز حد ساما (33٪)',
    resultsTitle: 'تقرير التقييم',
    decisionApproved: 'تم القبول',
    decisionRejected: 'تم الرفض',
    riskLevel: 'مستوى المخاطر',
    riskHigh: 'مرتفع',
    riskMedium: 'متوسط',
    riskLow: 'منخفض',
    creditScore: 'الدرجة الائتمانية',
    dbr: 'نسبة عبء الدين',
    shapTitle: 'العوامل المؤثرة في القرار',
    reason: 'سبب القرار',
    recommendation: 'التوصية',
    loading: 'جارٍ التحليل...',
    error: 'حدث خطأ. حاول مرة أخرى.',
    selectBankFirst: 'اختر البنك أولًا',
    simulateFirst: 'يجب محاكاة بيانات سمة أولًا',
    navModelPerformance: 'أداء النموذج',
    mpEyebrow: 'الشفافية',
    mpHeroTitle: 'تحت الغطاء',
    mpHeroSub: 'نموذج XGBoost لتقييم المخاطر الائتمانية، مدرَّب على أكثر من 300,000 طلب قرض حقيقي.',
    mpStatAuc: 'مؤشر AUC-ROC',
    mpStatAucDesc: 'احتمال أن يصنّف النموذج عميلًا متعثّرًا عشوائيًا أعلى مخاطرةً من عميل سليم عشوائي. القيمة 0.5 تعني تخمينًا عشوائيًا، والقيمة 1.0 تعني تمييزًا مثاليًا.',
    mpStatApplicants: 'متقدّم تم تقييمهم',
    mpStatApplicantsDesc: 'إجمالي المتقدّمين الذين جرى تقييمهم عبر التحقّق المتقاطع بخمس طيّات (5-fold). كل متقدّم سُجِّل بنموذج لم يره أثناء التدريب — تنبؤات «خارج الطيّات» (OOF)، وهي الطريقة غير المنحازة لقياس التعميم.',
    mpStatEce: 'درجة بريير (Brier)',
    mpStatEceDesc: 'متوسط مربع الفارق بين احتمالات التعثّر المتوقَّعة والنتائج الفعلية على تنبّؤات «خارج الطيّات» (OOF). الأقل أفضل: 0 مثالي، و0.25 يكافئ التخمين العشوائي.',
    mpFlowEyebrow: 'كيف يعمل',
    mpFlowTitle: 'كيف يُتَّخذ قرار الائتمان',
    mpStep: 'الخطوة',
    mpStep1: 'تُقدِّم طلبك (الراتب، مبلغ القرض، السجل الائتماني).',
    mpStep2: 'تُسحب بيانات سمة والتأمينات الاجتماعية تلقائيًا.',
    mpStep3: 'يتم احتساب 31 إشارة مخاطر من ملفك.',
    mpStep4: 'يُنتج النموذج احتمالية التعثر (PD).',
    mpStep5: 'يحدد حد سياسة البنك القبول أو الرفض.',
    mpChartsEyebrow: 'الأداء',
    mpChartsTitle: 'مؤشرات أداء النموذج',
    mpPolicyTitle: 'الأداء حسب سياسة البنك',
    mpPolicyHint: 'محسوبة فعليًا على مجموعة الاختبار المحجوزة (61,503 طلبًا) عند العتبتين اللتين تستخدمهما البنوك في هذا النظام.',
    mpPolicyConservative: 'البنك المحافظ — احتمال التعثّر ≥ 5٪',
    mpPolicyAggressive: 'البنك الجريء — احتمال التعثّر ≥ 15٪',
    mpPolicyLoading: 'جارٍ تحميل المقاييس...',
    mpPolicyError: 'تعذّر تحميل مقاييس الأداء.',
    mpPolicyMetricPrecision: 'الدقة (Precision)',
    mpPolicyMetricPrecisionDesc: 'من بين كل 100 متقدّم تم رفضه، هذا العدد منهم كان سيتعثّر فعلًا.',
    mpPolicyMetricRecall: 'الاسترجاع (Recall)',
    mpPolicyMetricRecallDesc: 'من بين كل 100 عميل سيتعثّرون، يلتقط النموذج هذا العدد منهم.',
    mpPolicyMetricApproval: 'نسبة القبول',
    mpPolicyMetricApprovalDesc: 'نسبة المتقدمين الذين يُقبَلون تحت هذه السياسة.',
    mpPolicyMetricF1: 'معدّل F1',
    mpPolicyMetricF1Desc: 'التوازن بين التقاط المتعثّرين وعدم رفض العملاء الجيّدين.',
    mpAucTitle: 'القدرة على التمييز (AUC-ROC)',
    mpAucLabel: 'قدرة تمييز قوية',
    mpAucScaleRandom: 'عشوائي',
    mpAucScaleGood: 'جيد',
    mpAucScaleExcellent: 'ممتاز',
    mpThresholdsTitle: 'القبول مقابل الاسترجاع لكل عتبة',
    mpThrConservative: 'محافظ (PD ≥ 5%)',
    mpThrAggressive: 'جريء (PD ≥ 15%)',
    mpApproval: 'نسبة القبول',
    mpRecall: 'نسبة الاسترجاع',
    mpRecallLabel: 'ما المقصود بالاسترجاع',
    mpRecallExplain: 'من بين كل 100 عميل سيتعثرون، يلتقط النموذج هذا العدد منهم.',
    mpCalibTitle: 'مخطط الموثوقية (المعايرة)',
    mpCalibPerfect: 'معايرة مثالية',
    mpCalibModel: 'النموذج',
    mpCalibHint: 'كلما اقترب الخط من القطر، كانت تنبؤات النموذج جديرة بالثقة.',
    mpDriversEyebrow: 'العوامل',
    mpDriversTitle: 'ما الذي ينظر إليه النموذج أكثر',
    mpImpactGood: 'تأثير إيجابي',
    mpImpactBad: 'تأثير سلبي',
    mpDriverBureauAvg: 'درجة سمة (المتوسط)',
    mpDriverBureau1: 'درجة سمة (المصدر 1)',
    mpDriverBureau2: 'درجة سمة (المصدر 2)',
    mpDriverBureau3: 'درجة سمة (المصدر 3)',
    mpDriverSimah: 'درجة سمة',
    mpDriverDbr: 'نسبة عبء الدين',
    mpDriverLti: 'نسبة القرض إلى الدخل',
    mpDriverAge: 'عمر المتقدم',
    mpDriverEmp: 'سنوات التوظيف',
    mpDriverInstall: 'القسط الشهري',
    mpDriverInstalLate: 'نسبة المدفوعات المتأخرة',
    mpDriverHistoryLen: 'طول السجل الائتماني',
    mpDriverLoanAmt: 'مبلغ القرض',
    mpDriverCardUtilMax: 'ذروة استخدام البطاقة',
    mpDriverCardActive: 'أشهر تفعيل البطاقة',
    mpDriverBureauAvgDesc: 'متوسط درجات الجهات الائتمانية الخارجية، أقوى مؤشر للجدارة.',
    mpDriverBureauDesc: 'درجة من جهة ائتمانية خارجية، تعكس السلوك الائتماني السابق.',
    mpDriverSimahDesc: 'الدرجة المعروضة (300–900) المشتقة من متوسط الجهات الائتمانية.',
    mpDriverDbrDesc: 'نسبة الالتزامات الشهرية للراتب — أعلى = مخاطر أكبر.',
    mpDriverLtiDesc: 'حجم القرض مقارنة بالدخل السنوي.',
    mpDriverAgeDesc: 'العمر مرتبط ارتباطًا غير خطي بالاستقرار المالي.',
    mpDriverEmpDesc: 'مدة التوظيف الأطول ترتبط بدخل أكثر استقرارًا.',
    mpDriverInstallDesc: 'حجم القسط مقارنة بالدخل الشهري.',
    mpDriverInstalLateDesc: 'نسبة الأقساط السابقة المسدّدة بعد موعدها — أقوى مؤشر سلوكي.',
    mpDriverHistoryLenDesc: 'منذ متى يحمل المتقدّم حسابات ائتمانية مفتوحة.',
    mpDriverLoanAmtDesc: 'إجمالي مبلغ القرض المطلوب — كلما زاد، زادت المخاطر.',
    mpDriverCardUtilMaxDesc: 'أعلى نسبة استخدام للبطاقة مقابل حدّها — دليل على الضغط المالي.',
    mpDriverCardActiveDesc: 'عدد أشهر استخدام البطاقة الائتمانية فعليًا.',
    drv_EXT_SOURCE_AVG: 'متوسط درجات الجهات الائتمانية الخارجية — أقوى مؤشر منفرد لاحتمال السداد.',
    drv_EXT_SOURCE_1: 'درجة من جهة ائتمانية خارجية (المصدر 1) تعكس السلوك الائتماني السابق.',
    drv_EXT_SOURCE_2: 'درجة من جهة ائتمانية خارجية (المصدر 2) تعكس السلوك الائتماني السابق.',
    drv_EXT_SOURCE_3: 'درجة من جهة ائتمانية خارجية (المصدر 3) تعكس السلوك الائتماني السابق.',
    drv_SIMAH_SCORE: 'الدرجة المعروضة (300–900) المشتقة من متوسط الجهات الائتمانية.',
    drv_AMT_CREDIT: 'إجمالي مبلغ القرض المطلوب — القروض الأكبر تحمل مخاطر أعلى.',
    drv_AMT_ANNUITY: 'القسط الشهري — الأقساط الأكبر ترفع احتمال التعثّر.',
    drv_AMT_INCOME_TOTAL: 'الدخل الشهري المُصرَّح به — الدخل الأعلى يقلّل المخاطر.',
    drv_YEARS_EMPLOYED: 'سنوات العمل لدى صاحب العمل الحالي — المدة الأطول ترتبط بدخل أكثر استقرارًا.',
    drv_AGE_YEARS: 'عمر المتقدّم — يرتبط ارتباطًا غير خطي بالاستقرار المالي.',
    drv_DBR: 'القسط الشهري كنسبة من الدخل الشهري — أعلى = عبء دين أكبر.',
    drv_CREDIT_INCOME_RATIO: 'نسبة مبلغ القرض إلى الدخل — النسب الأكبر تشير إلى تجاوز الطاقة الائتمانية.',
    drv_INSTAL_PCT_LATE: 'نسبة الأقساط السابقة المسدّدة متأخرة — أقوى مؤشر سلوكي للمخاطر.',
    drv_INSTAL_DAYS_LATE_MAX: 'أسوأ تأخير لقسط واحد بالأيام — يلتقط الأحداث السلبية النادرة.',
    drv_INSTAL_DAYS_LATE_MEAN: 'متوسط أيام التأخير عبر جميع الأقساط السابقة.',
    drv_INSTAL_PAYMENT_RATE: 'متوسط نسبة المبلغ المدفوع إلى القسط المستحق.',
    drv_BUREAU_CREDIT_AGE_MAX: 'طول أقدم حساب ائتماني — السجل الأطول يعني مخاطر أقل.',
    drv_BUREAU_MAX_OVERDUE: 'أعلى مبلغ متأخر تم تسجيله عبر حسابات الجهات الائتمانية.',
    drv_BUREAU_DAYS_OVERDUE_MAX: 'أطول فترة تأخير بالأيام عبر حسابات الجهات الائتمانية.',
    drv_BUREAU_DEBT_TOTAL: 'إجمالي الدين المستحق المُجمَّع عبر حسابات الجهات الائتمانية.',
    drv_BUREAU_LIMIT_TOTAL: 'إجمالي الحد الائتماني عبر حسابات الجهات الائتمانية.',
    drv_BUREAU_UTIL_RATIO: 'نسبة الدين إلى الحد الائتماني لدى الجهات الائتمانية — القيم العالية تشير إلى ضغط مالي.',
    drv_BUREAU_ACTIVE_COUNT: 'عدد القروض النشطة حاليًا لدى الجهات الائتمانية.',
    drv_BUREAU_PROLONGED_COUNT: 'عدد القروض التي تمّ تمديدها — التمديدات المتكرّرة علامة تحذيرية.',
    drv_CARD_UTIL_RATIO_AVG: 'متوسط رصيد البطاقة مقارنة بحدّها عبر السجل.',
    drv_CARD_UTIL_RATIO_MAX: 'ذروة استخدام البطاقة — القيم العالية تشير إلى ضغط مالي.',
    drv_CARD_DPD_MAX: 'أعلى عدد أيام تأخير على البطاقة في أي شهر.',
    drv_CARD_PAYMENT_RATIO: 'متوسط نسبة مدفوعات البطاقة إلى الرصيد.',
    drv_CARD_MONTHS_ACTIVE: 'عدد الأشهر التي استُخدمت فيها البطاقة الائتمانية فعليًا.',
    drv_IS_EMPLOYED: 'ما إذا كان المتقدّم في وظيفة مستقرة («Working» أو «State servant»).',
    drv_AMT_REQ_CREDIT_BUREAU_MON: 'عدد الاستعلامات الائتمانية في الشهر الأخير — تكرارها يدلّ على ضغط مالي.',
    drv_ANNUITY_CREDIT_RATIO: 'القسط الشهري كنسبة من إجمالي القرض — النسب الأعلى تعني فترة سداد أقصر وعبء شهري أكبر.',
    drv_GOODS_CREDIT_RATIO: 'سعر السلعة الممولة كنسبة من مبلغ القرض — كلما اقتربت من 1 كان مساهمة المتقدّم في الدفعة الأولى أقل.',
    drv_BUREAU_DEBT_CREDIT_RATIO_MAX: 'أعلى نسبة دين مستحق إلى إجمالي القرض عبر حسابات الجهات الائتمانية — مؤشر على ضغط الديون.',
    drv_OWN_CAR_AGE: 'عمر السيارة المملوكة بالسنوات — يرتبط بالاستقرار وعمر الأصول.',
    drv_CODE_GENDER_M: 'جنس المتقدّم (ذكر) — يستخدمه النموذج كميزة لكنه يستلزم مراجعة لاعتبارات العدالة.',
    mpFairnessEyebrow: 'الحدود',
    mpFairnessTitle: 'ما نعرفه عن حدود النموذج',
    mpFairAgeTitle: 'تحيّز العمر',
    mpFairAgeBody: 'نسبة قبول المتقدمين تحت 25 سنة 18% مقابل متوسط 48%. هذا يعكس مخاطر فعلية في البيانات لكن قد يتعارض مع التشريعات في بعض الدول.',
    mpFairBureauTitle: 'تركّز على درجات الجهات الائتمانية',
    mpFairBureauBody: 'يعتمد النموذج بشكل كبير على درجات الجهات الائتمانية الخارجية. إذا كانت بيانات الجهات مفقودة أو قديمة، قد تتراجع الدقة.',
    mpFairDisclaimerTitle: 'إخلاء مسؤولية المحاكاة',
    mpFairDisclaimerBody: 'تم تدريب النموذج على مجموعة بيانات Home Credit من Kaggle. هذا مشروع للعرض وليس مخصصًا لقرارات الإقراض الفعلية.',
  },
  en: {
    brand: 'Credit Risk Analyzer',
    navHome: 'Home',
    navHowItWorks: 'How it works',
    navResults: 'Results',
    navContact: 'Contact',
    getStarted: 'Get Started',
    heroEyebrow: 'Intelligent credit decisions',
    heroHeading: "Capital, data, and service redefining what 'growth' means.",
    heroSub: 'Real-time credit assessment powered by machine learning and SAMA-grade rules, delivering a clear decision in seconds.',
    ctaPrimary: 'Open Account',
    ctaSecondary: 'Explore Markets',
    statsTitle: 'Results that matter',
    statsSub: 'Real numbers that prove the difference we make.',
    stat1Value: '28%',
    stat1Label: 'Total return for optimized portfolios',
    stat2Value: '45 min/wk',
    stat2Label: 'Saved with automated trading strategies',
    stat3Value: 'SEC Compliant',
    stat3Label: 'Registered Investment Advisor — security and compliance',
    pickBank: 'Choose your bank profile',
    bankConservative: 'Conservative Bank',
    bankAggressive: 'Aggressive Bank',
    bankConservativeDesc: '2%–4% fixed rate, min salary SAR 5,000',
    bankAggressiveDesc: '7%–15% variable rate, min salary SAR 4,000',
    pdThreshold: 'PD threshold',
    minScore: 'Min SIMAH score',
    interestRate: 'Interest rate',
    formTitle: 'Application details',
    grossSalary: 'Monthly salary (SAR)',
    loanAmount: 'Loan amount (SAR)',
    loanMonths: 'Loan term (months)',
    employmentType: 'Employment',
    employmentGov: 'Government',
    employmentPriv: 'Private',
    employmentSelf: 'Self-employed',
    age: 'Age',
    submitBtn: 'Assess application',
    simulateBtn: 'Simulate Credit Bureau Pull (SIMAH + GOSI)',
    simahTitle: 'Credit profile (simulated)',
    simahTotalDebt: 'Total debt',
    simahMaxOverdue: 'Max overdue',
    simahInquiries: 'Inquiries (1 mo)',
    simahHistory: 'Avg history (days)',
    simahDpd: 'Max DPD',
    gosiTitle: 'GOSI profile (simulated)',
    gosiYears: 'Years of service',
    gosiSector: 'Employer sector',
    gosiStatus: 'Subscription status',
    gosiActive: 'Active',
    gosiSectorGov: 'Government',
    gosiSectorPriv: 'Private',
    gosiSectorSelf: 'Self-employed',
    gosiYearsUnit: 'yrs',
    gosiOverrideHint: 'Manual override enabled — sector is auto-filled from GOSI simulation but can be edited (simulation mode)',
    samaMinEmployment: 'Does not meet SAMA minimum employment requirement (Government: 3 months / Private: 12 months)',
    samaStatus: 'SAMA compliance',
    samaWithinGov: 'Within SAMA limit (45% for government)',
    samaWithinPriv: 'Within SAMA limit (33%)',
    samaExceedsGov: 'Exceeds SAMA limit (45% for government)',
    samaExceedsPriv: 'Exceeds SAMA limit (33%)',
    resultsTitle: 'Assessment report',
    decisionApproved: 'Approved',
    decisionRejected: 'Rejected',
    riskLevel: 'Risk level',
    riskHigh: 'High',
    riskMedium: 'Medium',
    riskLow: 'Low',
    creditScore: 'Credit score',
    dbr: 'Debt burden ratio',
    shapTitle: 'Decision drivers',
    reason: 'Reason',
    recommendation: 'Recommendation',
    loading: 'Analyzing...',
    error: 'Something went wrong. Please try again.',
    selectBankFirst: 'Select a bank first',
    simulateFirst: 'Simulate SIMAH first',
    navModelPerformance: 'Model Performance',
    mpEyebrow: 'Transparency',
    mpHeroTitle: 'Under the Hood',
    mpHeroSub: 'An XGBoost credit-risk model trained on 300,000+ real loan applications.',
    mpStatAuc: 'AUC-ROC',
    mpStatAucDesc: 'The probability that the model ranks a random defaulter as riskier than a random good customer. 0.5 means random guessing; 1.0 means perfect separation.',
    mpStatApplicants: 'applicants evaluated',
    mpStatApplicantsDesc: 'Total applicants evaluated via 5-fold cross-validation. Each applicant was scored by a model that never saw it during training — out-of-fold (OOF) predictions, the unbiased way to measure generalization.',
    mpStatEce: 'Brier score',
    mpStatEceDesc: 'Mean squared error between predicted default probabilities and actual outcomes on out-of-fold (OOF) predictions. Lower is better — 0 is perfect; 0.25 is the “always 0.5” baseline.',
    mpFlowEyebrow: 'How it works',
    mpFlowTitle: 'How a credit decision is made',
    mpStep: 'Step',
    mpStep1: 'You submit an application (salary, loan, history).',
    mpStep2: 'SIMAH + GOSI data is pulled automatically.',
    mpStep3: '31 risk signals are calculated from your profile.',
    mpStep4: 'The model produces a Probability of Default (PD).',
    mpStep5: "The bank's policy threshold determines approval or rejection.",
    mpChartsEyebrow: 'Performance',
    mpChartsTitle: 'Model performance',
    mpPolicyTitle: 'Performance by bank policy',
    mpPolicyHint: 'Computed live on the held-out test set (n = 61,503) at the two thresholds the banks in this system actually use.',
    mpPolicyConservative: 'Conservative Bank  PD  5%',
    mpPolicyAggressive: 'Aggressive Bank  PD  15%',
    mpPolicyLoading: 'Loading performance metrics…',
    mpPolicyError: 'Could not load performance metrics.',
    mpPolicyMetricPrecision: 'Precision',
    mpPolicyMetricPrecisionDesc: 'Of every 100 rejected applicants, this many would have actually defaulted',
    mpPolicyMetricRecall: 'Recall',
    mpPolicyMetricRecallDesc: 'Of every 100 customers who would default, the model catches this many',
    mpPolicyMetricApproval: 'Approval Rate',
    mpPolicyMetricApprovalDesc: 'Share of applicants approved under this policy',
    mpPolicyMetricF1: 'F1 Score',
    mpPolicyMetricF1Desc: 'Balance between catching defaulters and not rejecting good customers',
    mpAucTitle: 'Discriminative power (AUC-ROC)',
    mpAucLabel: 'Strong discriminative power',
    mpAucScaleRandom: 'Random',
    mpAucScaleGood: 'Good',
    mpAucScaleExcellent: 'Excellent',
    mpThresholdsTitle: 'Approval vs default catch-rate by threshold',
    mpThrConservative: 'Conservative (PD ≥ 5%)',
    mpThrAggressive: 'Aggressive (PD ≥ 15%)',
    mpApproval: 'Approval rate',
    mpRecall: 'Recall',
    mpRecallLabel: 'What recall means',
    mpRecallExplain: 'Out of 100 customers who would default, the model catches this many of them.',
    mpCalibTitle: 'Reliability diagram (calibration)',
    mpCalibPerfect: 'Perfect calibration',
    mpCalibModel: 'Model',
    mpCalibHint: 'Bars close to the diagonal = the model’s predictions are trustworthy.',
    mpDriversEyebrow: 'Drivers',
    mpDriversTitle: 'What the model looks at most',
    mpImpactGood: 'Lowers risk',
    mpImpactBad: 'Raises risk',
    mpDriverBureauAvg: 'Credit Bureau Score (Average)',
    mpDriverBureau1: 'Credit Bureau Score (Source 1)',
    mpDriverBureau2: 'Credit Bureau Score (Source 2)',
    mpDriverBureau3: 'Credit Bureau Score (Source 3)',
    mpDriverSimah: 'SIMAH Score',
    mpDriverDbr: 'Debt Burden Ratio',
    mpDriverLti: 'Loan-to-Income Ratio',
    mpDriverAge: 'Applicant Age',
    mpDriverEmp: 'Years of Employment',
    mpDriverInstall: 'Monthly Installment',
    mpDriverInstalLate: 'Late Payment Rate',
    mpDriverHistoryLen: 'Credit History Length',
    mpDriverLoanAmt: 'Loan Amount',
    mpDriverCardUtilMax: 'Credit Card Utilization (Maximum)',
    mpDriverCardActive: 'Credit Card Active Months',
    mpDriverBureauAvgDesc: 'Average of external bureau scores — the strongest single predictor of repayment.',
    mpDriverBureauDesc: 'A score from one external credit bureau, reflecting prior credit behavior.',
    mpDriverSimahDesc: 'The displayed 300–900 score derived from the average bureau signal.',
    mpDriverDbrDesc: 'Share of monthly income committed to debt — higher means greater risk.',
    mpDriverLtiDesc: 'Loan size relative to annual income.',
    mpDriverAgeDesc: 'Age relates non-linearly to financial stability.',
    mpDriverEmpDesc: 'Longer employment correlates with steadier income.',
    mpDriverInstallDesc: 'Installment size relative to monthly income.',
    mpDriverInstalLateDesc: 'Share of past installments paid late — the strongest behavioral signal.',
    mpDriverHistoryLenDesc: 'How long the applicant has held credit accounts.',
    mpDriverLoanAmtDesc: 'Total loan amount requested — bigger loans carry more risk.',
    mpDriverCardUtilMaxDesc: 'Peak credit-card balance against limit — high values signal financial stress.',
    mpDriverCardActiveDesc: 'How many months the credit card has actually been used.',
    drv_EXT_SOURCE_AVG: 'Average of external bureau scores — the strongest single predictor of repayment.',
    drv_EXT_SOURCE_1: 'Score from external bureau source 1, reflecting prior credit behavior.',
    drv_EXT_SOURCE_2: 'Score from external bureau source 2, reflecting prior credit behavior.',
    drv_EXT_SOURCE_3: 'Score from external bureau source 3, reflecting prior credit behavior.',
    drv_SIMAH_SCORE: 'The displayed 300–900 score derived from the average bureau signal.',
    drv_AMT_CREDIT: 'Total loan amount requested — bigger loans carry more risk.',
    drv_AMT_ANNUITY: 'Monthly installment amount — larger installments raise default risk.',
    drv_AMT_INCOME_TOTAL: 'Reported monthly income — higher income lowers risk.',
    drv_YEARS_EMPLOYED: 'Years at current employer — longer tenure correlates with steadier income.',
    drv_AGE_YEARS: 'Applicant age — relates non-linearly to financial stability.',
    drv_DBR: 'Monthly installment as a share of monthly income — higher means greater debt burden.',
    drv_CREDIT_INCOME_RATIO: 'Loan amount relative to income — bigger ratios signal stretched capacity.',
    drv_INSTAL_PCT_LATE: 'Share of past installments paid late — the strongest behavioral risk signal.',
    drv_INSTAL_DAYS_LATE_MAX: 'Worst single-installment delay in days — captures rare bad events.',
    drv_INSTAL_DAYS_LATE_MEAN: 'Average days late across all past installments.',
    drv_INSTAL_PAYMENT_RATE: 'Average ratio of paid amount to scheduled installment.',
    drv_BUREAU_CREDIT_AGE_MAX: 'Length of the longest credit account — longer history means lower risk.',
    drv_BUREAU_MAX_OVERDUE: 'Highest overdue amount ever recorded across bureau accounts.',
    drv_BUREAU_DAYS_OVERDUE_MAX: 'Longest stretch of overdue days across bureau accounts.',
    drv_BUREAU_DEBT_TOTAL: 'Total outstanding bureau debt summed across loans.',
    drv_BUREAU_LIMIT_TOTAL: 'Total credit limit across bureau accounts.',
    drv_BUREAU_UTIL_RATIO: 'Bureau debt as a share of bureau credit limit — high values flag stress.',
    drv_BUREAU_ACTIVE_COUNT: 'Number of currently active bureau loans.',
    drv_BUREAU_PROLONGED_COUNT: 'Number of loans the applicant prolonged — repeated extensions are a red flag.',
    drv_CARD_UTIL_RATIO_AVG: 'Average credit-card balance versus limit across history.',
    drv_CARD_UTIL_RATIO_MAX: 'Peak credit-card utilization — high values signal financial pressure.',
    drv_CARD_DPD_MAX: 'Maximum days-past-due on any credit-card month.',
    drv_CARD_PAYMENT_RATIO: 'Average ratio of card payments to balance.',
    drv_CARD_MONTHS_ACTIVE: 'How many months the credit card has actually been used.',
    drv_IS_EMPLOYED: 'Whether the applicant is in stable employment (“Working” or “State servant”).',
    drv_AMT_REQ_CREDIT_BUREAU_MON: 'Number of credit inquiries in the last month — bursts signal stress.',
    drv_ANNUITY_CREDIT_RATIO: 'Monthly installment as a share of the total loan — higher values mean a shorter term and heavier monthly burden.',
    drv_GOODS_CREDIT_RATIO: 'Price of the financed goods relative to the loan amount — closer to 1 means the applicant put down little of their own money.',
    drv_BUREAU_DEBT_CREDIT_RATIO_MAX: 'Largest outstanding-debt-to-credit-amount ratio across bureau accounts — a debt-pressure signal.',
    drv_OWN_CAR_AGE: 'Age of the applicant’s owned car in years — proxies stability and asset age.',
    drv_CODE_GENDER_M: 'Applicant gender (male) — used by the model as a feature but warrants fairness review.',
    mpFairnessEyebrow: 'Limits',
    mpFairnessTitle: 'What we know about the model’s limits',
    mpFairAgeTitle: 'Age bias',
    mpFairAgeBody: 'Applicants under 25 are approved at 18% vs 48% average. This reflects real risk in the data, but may conflict with regulations in some jurisdictions.',
    mpFairBureauTitle: 'Bureau-score concentration',
    mpFairBureauBody: 'The model relies heavily on external credit-bureau scores. If bureau data is missing or outdated, accuracy may degrade.',
    mpFairDisclaimerTitle: 'Simulation disclaimer',
    mpFairDisclaimerBody: 'This model was trained on the Home Credit dataset from Kaggle. It is a portfolio project and not intended for real lending decisions.',
  },
}
