export const STRINGS = {
  ar: {
    brand: 'محلل المخاطر الائتمانية',
    navHome: 'الرئيسية',
    navHowItWorks: 'كيف يعمل',
    navResults: 'النتائج',
    navContact: 'تواصل',
    getStarted: 'ابدأ الآن',
    heroEyebrow: 'منصة قرارات ائتمانية ذكية',
    heroHeading: 'من الطلب إلى القرار — في ثوانٍ.',
    heroSub: 'تحليل مخاطر ائتماني مدعوم بالذكاء الاصطناعي يقيّم ملفك فورًا وبعدالة.',
    heroDesc: 'مبني على بيانات ائتمانية حقيقية ونمذجة متقدمة، يقدّم نظامنا قرارات قبول موثوقة مع موازنة المخاطر والفرص.',
    ctaPrimary: 'تحقّق من أهليتي',
    ctaSecondary: 'اطلع على آلية العمل',
    navApply: 'تقديم طلب قرض',
    pickBank: 'محاكاة أسلوب قرار البنك',
    pickBankSub: 'شاهد كيف تؤثر استراتيجيات المخاطر للبنوك المختلفة على قرارات الموافقة على القروض الشخصية.',
    bankConservative: 'البنك المحافظ',
    bankAggressive: 'البنك الجريء',
    bankConservativeDesc: 'يحاكي بنكًا متحفظًا تجاه المخاطر يعطي الأولوية لانخفاض احتمال التعثر.',
    bankAggressiveDesc: 'يحاكي بنكًا يركّز على النمو ومستعدًا لقبول مخاطر أعلى من المتقدمين.',
    bankCardsDisclaimer: 'هذه محاكاة للقرار، ولا تمثّل عرض قرض حقيقي أو سعر فائدة أو منتجًا مصرفيًا.',
    pdThreshold: 'حد احتمالية التعثر',
    minScore: 'الحد الأدنى للدرجة الائتمانية',
    approvalStyle: 'أسلوب القبول',
    approvalStrict: 'صارم',
    approvalFlexible: 'مرن',
    formTitle: 'بيانات الطلب',
    grossSalary: 'الراتب الشهري (ريال)',
    loanAmount: 'مبلغ القرض (ريال)',
    loanMonths: 'مدة القرض (شهر)',
    employmentType: 'نوع التوظيف',
    employmentGov: 'حكومي',
    employmentPriv: 'خاص',
    employmentSelf: 'عمل حر',
    age: 'العمر',
    submitBtn: 'تقييم الطلب',
    simulateBtn: 'محاكاة ملف المتقدم',
    simahHelper: 'أنشئ ملفًا ائتمانيًا محاكيًا للمتقدم قبل تشغيل قرار القرض.',
    gosiHelper: 'يحاكي إشارات استقرار التوظيف والدخل المشابهة لما يراجعه البنك.',
    simahTitle: 'الملف الائتماني (محاكاة)',
    simahTotalDebt: 'إجمالي الدين',
    simahMaxOverdue: 'أعلى تأخر سداد',
    simahInquiries: 'استعلامات الشهر',
    simahHistory: 'متوسط عمر السجل (يوم)',
    simahDpd: 'أعلى تأخر بالأيام',
    gosiTitle: 'بيانات التأمينات (محاكاة)',
    gosiYears: 'سنوات الخدمة',
    gosiSector: 'قطاع صاحب العمل',
    gosiStatus: 'حالة الاشتراك',
    gosiActive: 'نشط',
    gosiSectorGov: 'حكومي',
    gosiSectorPriv: 'خاص',
    gosiSectorSelf: 'عمل حر',
    gosiYearsUnit: 'سنة',
    gosiOverrideHint: 'تجاوز يدوي مفعّل — يتم تعبئة القطاع تلقائيًا من محاكاة التأمينات ولكن يمكن تعديله (وضع المحاكاة)',
    samaMinEmployment: 'لا يستوفي الحد الأدنى لمدة الخدمة وفق ساما (حكومي: 3 أشهر / خاص: 12 شهرًا)',
    samaStatus: 'فحص قاعدة المحاكاة',
    samaWithinGov: 'ضمن حد قاعدة المحاكاة (45٪ للقطاع الحكومي)',
    samaWithinPriv: 'ضمن حد قاعدة المحاكاة (33٪)',
    samaExceedsGov: 'يتجاوز حد قاعدة المحاكاة (45٪ للقطاع الحكومي)',
    samaExceedsPriv: 'يتجاوز حد قاعدة المحاكاة (33٪)',
    resultsTitle: 'تقرير التقييم',
    decisionApproved: 'تم القبول',
    decisionRejected: 'تم الرفض',
    riskLevel: 'مستوى المخاطر',
    riskHigh: 'مرتفع',
    riskMedium: 'متوسط',
    riskLow: 'منخفض',
    creditScore: 'الدرجة الائتمانية',
    dbr: 'نسبة عبء الدين',
    shapTitle: 'العوامل المؤثرة في القرار',
    reason: 'سبب القرار',
    recommendation: 'التوصية',
    loading: 'جارٍ التحليل...',
    error: 'حدث خطأ. حاول مرة أخرى.',
    selectBankFirst: 'اختر البنك أولًا',
    simulateFirst: 'أنشئ ملف متقدم محاكى أولًا',
    navModelPerformance: 'أداء النموذج',
    mpEyebrow: 'الشفافية',
    mpHeroTitle: 'تحت الغطاء',
    mpHeroSub: 'يستخدم النظام خوارزمية XGBoost لتدريب نموذج مخاطر ائتمانية على بيانات قروض حقيقية واسعة النطاق (مجموعة Home Credit).',
    mpStatAuc: 'مؤشر AUC-ROC',
    mpStatAucDesc: 'يقيس مدى قدرة النموذج على ترتيب المتقدمين ذوي المخاطر العالية فوق المتقدمين ذوي المخاطر المنخفضة.',
    mpAucKaggleNote: 'AUC خارج الطيات: 0.7868 ± 0.0035 (مستقر عبر الطيات). للمقارنة، أعلى AUC على لوحة Kaggle لهذه البيانات كان 0.805.',
    mpStatApplicants: 'متقدّم تم تقييمهم',
    mpStatApplicantsDesc: 'إجمالي المتقدّمين الذين جرى تقييمهم عبر التحقّق المتقاطع بخمس طيّات (5-fold). كل متقدّم سُجِّل بنموذج لم يره أثناء التدريب — تنبؤات «خارج الطيّات» (OOF)، وهي الطريقة غير المنحازة لقياس التعميم.',
    mpStatEce: 'درجة بريير (Brier)',
    mpStatEceDesc: 'يقيس مدى دقة الاحتمالات المتوقعة. كلما كان الرقم أقل كان أفضل.',
    mpFlowEyebrow: 'كيف يعمل',
    mpFlowTitle: 'كيف يُتَّخذ قرار الائتمان',
    mpStep: 'الخطوة',
    mpStep1: 'تُقدِّم طلبك (الراتب، مبلغ القرض، السجل الائتماني).',
    mpStep2: 'تُولَّد إشارات محاكية لمكتب الائتمان (مشابهة لسمة) والتوظيف (مشابهة للتأمينات).',
    mpStep3: 'تُستخرج إشارات مخاطر متعددة من ملف المتقدم.',
    mpStep4: 'يُنتج النموذج احتمالية التعثر (PD).',
    mpStep5: 'يحدد حد سياسة البنك القبول أو الرفض.',
    mpChartsEyebrow: 'الأداء',
    mpChartsTitle: 'مؤشرات أداء النموذج',
    mpPolicyTitle: 'الأداء حسب سياسة البنك',
    mpPolicyHint: 'نتائج محاكاة توضح كيف تؤثر استراتيجيات البنوك المختلفة على قرارات القبول.',
    mpPolicyConservative: 'البنك المحافظ — احتمال التعثّر ≥ 5٪',
    mpPolicyAggressive: 'البنك الجريء — احتمال التعثّر ≥ 15٪',
    mpPolicyLoading: 'جارٍ تحميل المقاييس...',
    mpPolicyError: 'تعذّر تحميل مقاييس الأداء.',
    mpPolicyMetricPrecision: 'الدقة (Precision)',
    mpPolicyMetricPrecisionDesc: 'من بين كل 100 متقدّم تم رفضه، هذا العدد منهم كان سيتعثّر فعلًا.',
    mpPolicyMetricRecall: 'الاسترجاع (Recall)',
    mpPolicyMetricRecallDesc: 'من بين كل 100 عميل سيتعثّرون، يلتقط النموذج هذا العدد منهم.',
    mpPolicyMetricApproval: 'نسبة القبول',
    mpPolicyMetricApprovalDesc: 'نسبة المتقدمين الذين يُقبَلون تحت هذه السياسة.',
    mpPolicyMetricF1: 'معدّل F1',
    mpPolicyMetricF1Desc: 'التوازن بين التقاط المتعثّرين وعدم رفض العملاء الجيّدين.',
    mpAucTitle: 'القدرة على التمييز (AUC-ROC)',
    mpAucLabel: 'قدرة تمييز قوية',
    mpAucScaleRandom: 'عشوائي',
    mpAucScaleGood: 'جيد',
    mpAucScaleExcellent: 'ممتاز',
    mpThresholdsTitle: 'القبول مقابل الاسترجاع لكل عتبة',
    mpThrConservative: 'محافظ (PD ≥ 5%)',
    mpThrAggressive: 'جريء (PD ≥ 15%)',
    mpApproval: 'نسبة القبول',
    mpRecall: 'نسبة الاسترجاع',
    mpRecallLabel: 'ما المقصود بالاسترجاع',
    mpRecallExplain: 'من بين كل 100 عميل سيتعثرون، يلتقط النموذج هذا العدد منهم.',
    mpCalibTitle: 'مخطط الموثوقية (المعايرة)',
    mpCalibPerfect: 'معايرة مثالية',
    mpCalibModel: 'النموذج',
    mpCalibHint: 'كلما اقترب الخط من القطر، كانت تنبؤات النموذج جديرة بالثقة.',
    mpDriversEyebrow: 'العوامل',
    mpDriversTitle: 'ما الذي ينظر إليه النموذج أكثر',
    mpImpactGood: 'تأثير إيجابي',
    mpImpactBad: 'تأثير سلبي',
    mpDriverBureauAvg: 'قوة السجل الائتماني العامة',
    mpDriverBureau1: 'قوة السجل الائتماني',
    mpDriverBureau2: 'درجة سلوك السداد',
    mpDriverBureau3: 'درجة الملف الائتماني الخارجي',
    mpDriverSimah: 'درجة ائتمانية محاكاة',
    mpDriverDbr: 'نسبة عبء الدين',
    mpDriverLti: 'نسبة القرض إلى الدخل',
    mpDriverAge: 'عمر المتقدم',
    mpDriverEmp: 'سنوات التوظيف',
    mpDriverInstall: 'القسط الشهري',
    mpDriverInstalLate: 'نسبة المدفوعات المتأخرة',
    mpDriverHistoryLen: 'طول السجل الائتماني',
    mpDriverLoanAmt: 'مبلغ القرض',
    mpDriverCardUtilMax: 'أعلى استخدام للبطاقة',
    mpDriverCardActive: 'نشاط البطاقة الحديث',
    mpDriverBureauAvgDesc: 'متوسط درجات الجهات الائتمانية الخارجية، أقوى مؤشر للجدارة.',
    mpDriverBureauDesc: 'درجة من جهة ائتمانية خارجية، تعكس السلوك الائتماني السابق.',
    mpDriverSimahDesc: 'الدرجة المعروضة (300–900) المشتقة من متوسط الجهات الائتمانية.',
    mpDriverDbrDesc: 'نسبة الالتزامات الشهرية للراتب — أعلى = مخاطر أكبر.',
    mpDriverLtiDesc: 'حجم القرض مقارنة بالدخل السنوي.',
    mpDriverAgeDesc: 'العمر مرتبط ارتباطًا غير خطي بالاستقرار المالي.',
    mpDriverEmpDesc: 'مدة التوظيف الأطول ترتبط بدخل أكثر استقرارًا.',
    mpDriverInstallDesc: 'حجم القسط مقارنة بالدخل الشهري.',
    mpDriverInstalLateDesc: 'نسبة الأقساط السابقة المسدّدة بعد موعدها — أقوى مؤشر سلوكي.',
    mpDriverHistoryLenDesc: 'منذ متى يحمل المتقدّم حسابات ائتمانية مفتوحة.',
    mpDriverLoanAmtDesc: 'إجمالي مبلغ القرض المطلوب — كلما زاد، زادت المخاطر.',
    mpDriverCardUtilMaxDesc: 'أعلى نسبة استخدام للبطاقة مقابل حدّها — دليل على الضغط المالي.',
    mpDriverCardActiveDesc: 'عدد أشهر استخدام البطاقة الائتمانية فعليًا.',
    drv_EXT_SOURCE_AVG: 'ملخص عام لقوة السجل الائتماني وسلوك السداد السابق.',
    drv_EXT_SOURCE_1: 'مؤشر مبسط لقوة السجل الائتماني السابق.',
    drv_EXT_SOURCE_2: 'مؤشر يوضح مدى انتظام المتقدم في السداد.',
    drv_EXT_SOURCE_3: 'مؤشر إضافي لجودة الملف الائتماني العام.',
    drv_SIMAH_SCORE: 'درجة ائتمانية محاكاة بين 300 و900.',
    drv_AMT_CREDIT: 'إجمالي مبلغ القرض المطلوب — القروض الأكبر تحمل مخاطر أعلى.',
    drv_AMT_ANNUITY: 'القسط الشهري — الأقساط الأكبر ترفع احتمال التعثّر.',
    drv_AMT_INCOME_TOTAL: 'الدخل الشهري المُصرَّح به — الدخل الأعلى يقلّل المخاطر.',
    drv_YEARS_EMPLOYED: 'سنوات العمل لدى صاحب العمل الحالي — المدة الأطول ترتبط بدخل أكثر استقرارًا.',
    drv_AGE_YEARS: 'عمر المتقدّم — يرتبط ارتباطًا غير خطي بالاستقرار المالي.',
    drv_DBR: 'القسط الشهري كنسبة من الدخل الشهري — أعلى = عبء دين أكبر.',
    drv_CREDIT_INCOME_RATIO: 'نسبة مبلغ القرض إلى الدخل — النسب الأكبر تشير إلى تجاوز الطاقة الائتمانية.',
    drv_INSTAL_PCT_LATE: 'نسبة الأقساط السابقة المسدّدة متأخرة — أقوى مؤشر سلوكي للمخاطر.',
    drv_INSTAL_DAYS_LATE_MAX: 'أسوأ تأخير لقسط واحد بالأيام — يلتقط الأحداث السلبية النادرة.',
    drv_INSTAL_DAYS_LATE_MEAN: 'متوسط أيام التأخير عبر جميع الأقساط السابقة.',
    drv_INSTAL_PAYMENT_RATE: 'متوسط نسبة المبلغ المدفوع إلى القسط المستحق.',
    drv_BUREAU_CREDIT_AGE_MAX: 'طول أقدم سجل ائتماني — السجل الأطول عادة يعني مخاطر أقل.',
    drv_BUREAU_MAX_OVERDUE: 'أعلى رصيد متأخر ظهر في السجل الائتماني.',
    drv_BUREAU_DAYS_OVERDUE_MAX: 'أطول فترة تأخير في السداد.',
    drv_BUREAU_DEBT_TOTAL: 'إجمالي الالتزامات الائتمانية الحالية.',
    drv_BUREAU_LIMIT_TOTAL: 'إجمالي الحد الائتماني المتاح.',
    drv_BUREAU_UTIL_RATIO: 'مستوى استخدام الائتمان المتاح — القيم العالية تشير إلى ضغط مالي.',
    drv_BUREAU_ACTIVE_COUNT: 'عدد القروض النشطة حاليًا.',
    drv_BUREAU_PROLONGED_COUNT: 'عدد القروض التي تمّ تمديدها — التمديدات المتكرّرة علامة تحذيرية.',
    drv_CARD_UTIL_RATIO_AVG: 'متوسط رصيد البطاقة مقارنة بحدّها عبر السجل.',
    drv_CARD_UTIL_RATIO_MAX: 'ذروة استخدام البطاقة — القيم العالية تشير إلى ضغط مالي.',
    drv_CARD_DPD_MAX: 'أعلى عدد أيام تأخير على البطاقة في أي شهر.',
    drv_CARD_PAYMENT_RATIO: 'متوسط نسبة مدفوعات البطاقة إلى الرصيد.',
    drv_CARD_MONTHS_ACTIVE: 'عدد الأشهر التي استُخدمت فيها البطاقة الائتمانية فعليًا.',
    drv_IS_EMPLOYED: 'ما إذا كان المتقدّم لديه وظيفة مستقرة.',
    drv_AMT_REQ_CREDIT_BUREAU_MON: 'عدد الاستعلامات الائتمانية في الشهر الأخير — تكرارها يدلّ على ضغط مالي.',
    drv_ANNUITY_CREDIT_RATIO: 'القسط الشهري كنسبة من إجمالي القرض — النسب الأعلى تعني فترة سداد أقصر وعبء شهري أكبر.',
    drv_GOODS_CREDIT_RATIO: 'سعر السلعة الممولة كنسبة من مبلغ القرض — كلما اقتربت من 1 كان مساهمة المتقدّم في الدفعة الأولى أقل.',
    drv_BUREAU_DEBT_CREDIT_RATIO_MAX: 'أعلى نسبة دين مستحق إلى إجمالي القرض عبر حسابات الجهات الائتمانية — مؤشر على ضغط الديون.',
    drv_OWN_CAR_AGE: 'عمر السيارة المملوكة بالسنوات — يرتبط بالاستقرار وعمر الأصول.',
    drv_CODE_GENDER_M: 'جنس المتقدّم (ذكر) — يستخدمه النموذج كميزة لكنه يستلزم مراجعة لاعتبارات العدالة.',
    feat_EXT_SOURCE_AVG: 'قوة السجل الائتماني العامة',
    feat_EXT_SOURCE_1: 'قوة السجل الائتماني',
    feat_EXT_SOURCE_2: 'درجة سلوك السداد',
    feat_EXT_SOURCE_3: 'درجة الملف الائتماني الخارجي',
    feat_SIMAH_SCORE: 'درجة ائتمانية محاكاة',
    feat_AMT_CREDIT: 'مبلغ القرض المطلوب',
    feat_AMT_GOODS_PRICE: 'قيمة الشيء المموّل التقديرية',
    feat_AMT_ANNUITY: 'القسط الشهري',
    feat_AMT_INCOME_TOTAL: 'الدخل الشهري',
    feat_YEARS_EMPLOYED: 'مدة التوظيف',
    feat_AGE_YEARS: 'عمر المتقدم',
    feat_DBR: 'عبء الدين الشهري',
    feat_CREDIT_INCOME_RATIO: 'حجم القرض مقارنة بالدخل',
    feat_INSTAL_PCT_LATE: 'تاريخ المدفوعات المتأخرة',
    feat_INSTAL_DAYS_LATE_MAX: 'أسوأ تأخير في السداد',
    feat_INSTAL_DAYS_LATE_MEAN: 'متوسط تأخير السداد',
    feat_INSTAL_PAYMENT_RATE: 'انتظام السداد السابق',
    feat_BUREAU_CREDIT_AGE_MAX: 'طول السجل الائتماني',
    feat_BUREAU_MAX_OVERDUE: 'أعلى رصيد متأخر',
    feat_BUREAU_DAYS_OVERDUE_MAX: 'أطول فترة تأخير',
    feat_BUREAU_DEBT_TOTAL: 'الالتزامات الائتمانية الحالية',
    feat_BUREAU_LIMIT_TOTAL: 'الحد الائتماني المتاح',
    feat_BUREAU_UTIL_RATIO: 'مستوى استخدام الائتمان',
    feat_BUREAU_ACTIVE_COUNT: 'عدد القروض النشطة',
    feat_BUREAU_PROLONGED_COUNT: 'تمديدات القروض المتكررة',
    feat_CARD_UTIL_RATIO_AVG: 'متوسط استخدام البطاقة',
    feat_CARD_UTIL_RATIO_MAX: 'أعلى استخدام للبطاقة',
    feat_CARD_DPD_MAX: 'أسوأ تأخير في سداد البطاقة',
    feat_CARD_PAYMENT_RATIO: 'انتظام سداد البطاقة',
    feat_CARD_MONTHS_ACTIVE: 'نشاط البطاقة الحديث',
    feat_IS_EMPLOYED: 'استقرار الوظيفة',
    feat_AMT_REQ_CREDIT_BUREAU_MON: 'طلبات الائتمان الحديثة',
    feat_ANNUITY_CREDIT_RATIO: 'ضغط القسط الشهري',
    feat_GOODS_CREDIT_RATIO: 'المبلغ الممول مقارنة بقيمة الشيء',
    feat_BUREAU_DEBT_CREDIT_RATIO_MAX: 'أعلى ضغط دين على الائتمان الحالي',
    feat_OWN_CAR_AGE: 'عمر السيارة',
    feat_CODE_GENDER_M: 'جنس المتقدم',
    mpFairnessEyebrow: 'الحدود',
    mpFairnessTitle: 'ما نعرفه عن حدود النموذج',
    mpFairAgeTitle: 'تحيّز العمر',
    mpFairAgeBody: 'نسبة قبول المتقدمين تحت 25 سنة 18% مقابل متوسط 48%. هذا يعكس مخاطر فعلية في البيانات لكن قد يتعارض مع التشريعات في بعض الدول.',
    mpFairBureauTitle: 'تركّز على درجات الجهات الائتمانية',
    mpFairBureauBody: 'يعتمد النموذج بشكل كبير على درجات الجهات الائتمانية الخارجية. إذا كانت بيانات الجهات مفقودة أو قديمة، قد تتراجع الدقة.',
  },
  en: {
    brand: 'Credit Risk Analyzer',
    navHome: 'Home',
    navHowItWorks: 'How it works',
    navResults: 'Results',
    navContact: 'Contact',
    getStarted: 'Get Started',
    heroEyebrow: 'Intelligent credit decisions',
    heroHeading: 'From application to decision — in seconds.',
    heroSub: 'AI-powered credit risk analysis that evaluates your profile instantly and fairly.',
    heroDesc: 'Built on real credit data and advanced modeling, our system provides reliable approval decisions while balancing risk and opportunity.',
    ctaPrimary: 'Check My Eligibility',
    ctaSecondary: 'See How It Works',
    navApply: 'Apply for a loan',
    pickBank: 'Simulate Bank Decision Style',
    pickBankSub: 'See how different bank risk strategies affect personal loan approval decisions.',
    bankConservative: 'Conservative Bank',
    bankAggressive: 'Aggressive Bank',
    bankConservativeDesc: 'Simulates a risk-averse bank that prioritizes low default probability.',
    bankAggressiveDesc: 'Simulates a growth-focused bank willing to accept higher applicant risk.',
    bankCardsDisclaimer: 'This is a decision simulation. It does not represent a real loan offer, interest rate, or banking product.',
    pdThreshold: 'PD threshold',
    minScore: 'Min credit score',
    approvalStyle: 'Approval Style',
    approvalStrict: 'Strict',
    approvalFlexible: 'Flexible',
    formTitle: 'Application details',
    grossSalary: 'Monthly salary (SAR)',
    loanAmount: 'Loan amount (SAR)',
    loanMonths: 'Loan term (months)',
    employmentType: 'Employment',
    employmentGov: 'Government',
    employmentPriv: 'Private',
    employmentSelf: 'Self-employed',
    age: 'Age',
    submitBtn: 'Assess application',
    simulateBtn: 'Simulate Applicant Profile',
    simahHelper: 'Generate a simulated applicant credit profile before running the loan decision.',
    gosiHelper: 'Simulates employment stability and income-related signals similar to what a bank might review.',
    simahTitle: 'Credit profile (simulated)',
    simahTotalDebt: 'Total debt',
    simahMaxOverdue: 'Max overdue',
    simahInquiries: 'Inquiries (1 mo)',
    simahHistory: 'Avg history (days)',
    simahDpd: 'Max DPD',
    gosiTitle: 'GOSI profile (simulated)',
    gosiYears: 'Years of service',
    gosiSector: 'Employer sector',
    gosiStatus: 'Subscription status',
    gosiActive: 'Active',
    gosiSectorGov: 'Government',
    gosiSectorPriv: 'Private',
    gosiSectorSelf: 'Self-employed',
    gosiYearsUnit: 'yrs',
    gosiOverrideHint: 'Manual override enabled — sector is auto-filled from GOSI simulation but can be edited (simulation mode)',
    samaMinEmployment: 'Does not meet SAMA minimum employment requirement (Government: 3 months / Private: 12 months)',
    samaStatus: 'Simulation rule check',
    samaWithinGov: 'Within simulation rule limit (45% for government)',
    samaWithinPriv: 'Within simulation rule limit (33%)',
    samaExceedsGov: 'Exceeds simulation rule limit (45% for government)',
    samaExceedsPriv: 'Exceeds simulation rule limit (33%)',
    resultsTitle: 'Assessment report',
    decisionApproved: 'Approved',
    decisionRejected: 'Rejected',
    riskLevel: 'Risk level',
    riskHigh: 'High',
    riskMedium: 'Medium',
    riskLow: 'Low',
    creditScore: 'Credit score',
    dbr: 'Debt burden ratio',
    shapTitle: 'Decision drivers',
    reason: 'Reason',
    recommendation: 'Recommendation',
    loading: 'Analyzing...',
    error: 'Something went wrong. Please try again.',
    selectBankFirst: 'Select a bank first',
    simulateFirst: 'Generate a simulated applicant profile first',
    navModelPerformance: 'Model Performance',
    mpEyebrow: 'Transparency',
    mpHeroTitle: 'Under the Hood: XGBoost algorithm',
    mpHeroSub: 'Uses the XGBoost algorithm to train a credit-risk model on large-scale real-world loan data (Home Credit dataset).',
    mpStatAuc: 'AUC-ROC',
    mpStatAucDesc: 'Measures how well the model ranks high-risk applicants above low-risk ones.',
    mpAucKaggleNote: 'OOF AUC: 0.7868 ± 0.0035 (stable across folds). For reference, the top Kaggle leaderboard AUC on this dataset was 0.805.',
    mpStatApplicants: 'applicants evaluated',
    mpStatApplicantsDesc: 'Total applicants evaluated via 5-fold cross-validation. Each applicant was scored by a model that never saw it during training — out-of-fold (OOF) predictions, the unbiased way to measure generalization.',
    mpStatEce: 'Brier score',
    mpStatEceDesc: 'Measures how accurate predicted probabilities are. Lower is better.',
    mpFlowEyebrow: 'How it works',
    mpFlowTitle: 'How a credit decision is made',
    mpStep: 'Step',
    mpStep1: 'You submit an application (salary, loan, history).',
    mpStep2: 'Simulated credit bureau (SIMAH-like) and employment (GOSI-like) signals are generated.',
    mpStep3: 'Multiple risk signals are derived from the applicant profile.',
    mpStep4: 'The model produces a Probability of Default (PD).',
    mpStep5: "The bank's policy threshold determines approval or rejection.",
    mpChartsEyebrow: 'Performance',
    mpChartsTitle: 'Model performance',
    mpPolicyTitle: 'Performance by bank policy',
    mpPolicyHint: 'Simulated results showing how different bank strategies affect approval decisions.',
    mpPolicyConservative: 'Conservative Bank  PD  5%',
    mpPolicyAggressive: 'Aggressive Bank  PD  15%',
    mpPolicyLoading: 'Loading performance metrics…',
    mpPolicyError: 'Could not load performance metrics.',
    mpPolicyMetricPrecision: 'Precision',
    mpPolicyMetricPrecisionDesc: 'Of every 100 rejected applicants, this many would have actually defaulted',
    mpPolicyMetricRecall: 'Recall',
    mpPolicyMetricRecallDesc: 'Of every 100 customers who would default, the model catches this many',
    mpPolicyMetricApproval: 'Approval Rate',
    mpPolicyMetricApprovalDesc: 'Share of applicants approved under this policy',
    mpPolicyMetricF1: 'F1 Score',
    mpPolicyMetricF1Desc: 'Balance between catching defaulters and not rejecting good customers',
    mpAucTitle: 'Discriminative power (AUC-ROC)',
    mpAucLabel: 'Strong discriminative power',
    mpAucScaleRandom: 'Random',
    mpAucScaleGood: 'Good',
    mpAucScaleExcellent: 'Excellent',
    mpThresholdsTitle: 'Approval vs default catch-rate by threshold',
    mpThrConservative: 'Conservative (PD ≥ 5%)',
    mpThrAggressive: 'Aggressive (PD ≥ 15%)',
    mpApproval: 'Approval rate',
    mpRecall: 'Recall',
    mpRecallLabel: 'What recall means',
    mpRecallExplain: 'Out of 100 customers who would default, the model catches this many of them.',
    mpCalibTitle: 'Reliability diagram (calibration)',
    mpCalibPerfect: 'Perfect calibration',
    mpCalibModel: 'Model',
    mpCalibHint: 'Bars close to the diagonal = the model’s predictions are trustworthy.',
    mpDriversEyebrow: 'Drivers',
    mpDriversTitle: 'What the model looks at most',
    mpImpactGood: 'Lowers risk',
    mpImpactBad: 'Raises risk',
    mpDriverBureauAvg: 'Overall credit history strength',
    mpDriverBureau1: 'Credit history strength',
    mpDriverBureau2: 'Repayment behavior score',
    mpDriverBureau3: 'External credit profile score',
    mpDriverSimah: 'Simulated credit score',
    mpDriverDbr: 'Monthly debt burden',
    mpDriverLti: 'Loan size compared with income',
    mpDriverAge: 'Applicant Age',
    mpDriverEmp: 'Years of Employment',
    mpDriverInstall: 'Monthly Installment',
    mpDriverInstalLate: 'Late Payment Rate',
    mpDriverHistoryLen: 'Credit History Length',
    mpDriverLoanAmt: 'Loan Amount',
    mpDriverCardUtilMax: 'Highest card usage',
    mpDriverCardActive: 'Recent card activity',
    mpDriverBureauAvgDesc: 'Average of external bureau scores — the strongest single predictor of repayment.',
    mpDriverBureauDesc: 'A score from one external credit bureau, reflecting prior credit behavior.',
    mpDriverSimahDesc: 'The displayed 300–900 score derived from the average bureau signal.',
    mpDriverDbrDesc: 'Share of monthly income committed to debt — higher means greater risk.',
    mpDriverLtiDesc: 'Loan size relative to annual income.',
    mpDriverAgeDesc: 'Age relates non-linearly to financial stability.',
    mpDriverEmpDesc: 'Longer employment correlates with steadier income.',
    mpDriverInstallDesc: 'Installment size relative to monthly income.',
    mpDriverInstalLateDesc: 'Share of past installments paid late — the strongest behavioral signal.',
    mpDriverHistoryLenDesc: 'How long the applicant has held credit accounts.',
    mpDriverLoanAmtDesc: 'Total loan amount requested — bigger loans carry more risk.',
    mpDriverCardUtilMaxDesc: 'Peak credit-card balance against limit — high values signal financial stress.',
    mpDriverCardActiveDesc: 'How many months the credit card has actually been used.',
    drv_EXT_SOURCE_AVG: 'A summary of credit history strength and previous repayment behavior.',
    drv_EXT_SOURCE_1: 'A simplified indicator of previous credit history strength.',
    drv_EXT_SOURCE_2: 'An indicator of how consistently the applicant has repaid obligations.',
    drv_EXT_SOURCE_3: 'An additional indicator of overall credit profile quality.',
    drv_SIMAH_SCORE: 'A simulated credit score between 300 and 900.',
    drv_AMT_CREDIT: 'Total loan amount requested — bigger loans carry more risk.',
    drv_AMT_ANNUITY: 'Monthly installment amount — larger installments raise default risk.',
    drv_AMT_INCOME_TOTAL: 'Reported monthly income — higher income lowers risk.',
    drv_YEARS_EMPLOYED: 'Years at current employer — longer tenure correlates with steadier income.',
    drv_AGE_YEARS: 'Applicant age — relates non-linearly to financial stability.',
    drv_DBR: 'Monthly installment as a share of monthly income — higher means greater debt burden.',
    drv_CREDIT_INCOME_RATIO: 'Loan amount relative to income — bigger ratios signal stretched capacity.',
    drv_INSTAL_PCT_LATE: 'Share of past installments paid late — the strongest behavioral risk signal.',
    drv_INSTAL_DAYS_LATE_MAX: 'Worst single-installment delay in days — captures rare bad events.',
    drv_INSTAL_DAYS_LATE_MEAN: 'Average days late across all past installments.',
    drv_INSTAL_PAYMENT_RATE: 'Average ratio of paid amount to scheduled installment.',
    drv_BUREAU_CREDIT_AGE_MAX: 'Length of the oldest credit history — longer history usually means lower risk.',
    drv_BUREAU_MAX_OVERDUE: 'Highest overdue balance seen in the credit history.',
    drv_BUREAU_DAYS_OVERDUE_MAX: 'Longest payment delay period.',
    drv_BUREAU_DEBT_TOTAL: 'Total current credit obligations.',
    drv_BUREAU_LIMIT_TOTAL: 'Total available credit limit.',
    drv_BUREAU_UTIL_RATIO: 'How much available credit is being used — high values can signal financial pressure.',
    drv_BUREAU_ACTIVE_COUNT: 'Number of currently active loans.',
    drv_BUREAU_PROLONGED_COUNT: 'Number of loans the applicant prolonged — repeated extensions are a red flag.',
    drv_CARD_UTIL_RATIO_AVG: 'Average credit-card balance versus limit across history.',
    drv_CARD_UTIL_RATIO_MAX: 'Peak credit-card utilization — high values signal financial pressure.',
    drv_CARD_DPD_MAX: 'Maximum days-past-due on any credit-card month.',
    drv_CARD_PAYMENT_RATIO: 'Average ratio of card payments to balance.',
    drv_CARD_MONTHS_ACTIVE: 'How many months the credit card has actually been used.',
    drv_IS_EMPLOYED: 'Whether the applicant appears to have stable employment.',
    drv_AMT_REQ_CREDIT_BUREAU_MON: 'Number of credit inquiries in the last month — bursts signal stress.',
    drv_ANNUITY_CREDIT_RATIO: 'Monthly installment as a share of the total loan — higher values mean a shorter term and heavier monthly burden.',
    drv_GOODS_CREDIT_RATIO: 'Price of the financed goods relative to the loan amount — closer to 1 means the applicant put down little of their own money.',
    drv_BUREAU_DEBT_CREDIT_RATIO_MAX: 'Largest outstanding-debt-to-credit-amount ratio across bureau accounts — a debt-pressure signal.',
    drv_OWN_CAR_AGE: 'Age of the applicant’s owned car in years — proxies stability and asset age.',
    drv_CODE_GENDER_M: 'Applicant gender (male) — used by the model as a feature but warrants fairness review.',
    feat_EXT_SOURCE_AVG: 'Overall credit history strength',
    feat_EXT_SOURCE_1: 'Credit history strength',
    feat_EXT_SOURCE_2: 'Repayment behavior score',
    feat_EXT_SOURCE_3: 'External credit profile score',
    feat_SIMAH_SCORE: 'Simulated credit score',
    feat_AMT_CREDIT: 'Requested loan amount',
    feat_AMT_GOODS_PRICE: 'Estimated financed item value',
    feat_AMT_ANNUITY: 'Monthly payment amount',
    feat_AMT_INCOME_TOTAL: 'Monthly income',
    feat_YEARS_EMPLOYED: 'Employment length',
    feat_AGE_YEARS: 'Applicant age',
    feat_DBR: 'Monthly debt burden',
    feat_CREDIT_INCOME_RATIO: 'Loan size compared with income',
    feat_INSTAL_PCT_LATE: 'Late payment history',
    feat_INSTAL_DAYS_LATE_MAX: 'Worst payment delay',
    feat_INSTAL_DAYS_LATE_MEAN: 'Average payment delay',
    feat_INSTAL_PAYMENT_RATE: 'Past payment consistency',
    feat_BUREAU_CREDIT_AGE_MAX: 'Credit history length',
    feat_BUREAU_MAX_OVERDUE: 'Highest overdue balance',
    feat_BUREAU_DAYS_OVERDUE_MAX: 'Longest overdue period',
    feat_BUREAU_DEBT_TOTAL: 'Existing credit obligations',
    feat_BUREAU_LIMIT_TOTAL: 'Available credit limit',
    feat_BUREAU_UTIL_RATIO: 'Credit usage level',
    feat_BUREAU_ACTIVE_COUNT: 'Number of active loans',
    feat_BUREAU_PROLONGED_COUNT: 'Repeated loan extensions',
    feat_CARD_UTIL_RATIO_AVG: 'Average card usage',
    feat_CARD_UTIL_RATIO_MAX: 'Highest card usage',
    feat_CARD_DPD_MAX: 'Worst card payment delay',
    feat_CARD_PAYMENT_RATIO: 'Card repayment consistency',
    feat_CARD_MONTHS_ACTIVE: 'Recent card activity',
    feat_IS_EMPLOYED: 'Stable employment status',
    feat_AMT_REQ_CREDIT_BUREAU_MON: 'Recent credit applications',
    feat_ANNUITY_CREDIT_RATIO: 'Monthly payment pressure',
    feat_GOODS_CREDIT_RATIO: 'Financed amount compared with item value',
    feat_BUREAU_DEBT_CREDIT_RATIO_MAX: 'Highest debt pressure on existing credit',
    feat_OWN_CAR_AGE: 'Vehicle age',
    feat_CODE_GENDER_M: 'Applicant gender',
    mpFairnessEyebrow: 'Limits',
    mpFairnessTitle: 'What we know about the model’s limits',
    mpFairAgeTitle: 'Age bias',
    mpFairAgeBody: 'Applicants under 25 are approved at 18% vs 48% average. This reflects real risk in the data, but may conflict with regulations in some jurisdictions.',
    mpFairBureauTitle: 'Bureau-score concentration',
    mpFairBureauBody: 'The model relies heavily on external credit-bureau scores. If bureau data is missing or outdated, accuracy may degrade.',
  },
}
